STRINGS = {
    "english": {
        "header_title": "Shopping List Preparer",
        "restart_app": "Restart the application to apply changes",
        "dishes_list": "Dishes list",
        "budget_cap": "Enter your maximum budget",
        "dish_selector": "Add a dish",
        "add_dish": "Add a dish to the list",
        "remove_elt": "Remove an element",
        "remove_entirely_elt": "Remove entirely the element",
        "no_dish": "No dish selected",
        "ingredients": "Ingredients",
        "ingredient_name": "Ingredient's name",
        "next_meals": "Next meals:",
        "ERR_dish_name": "Enter a name to your dish.",
        "ERR_dish_ingredients": "Add ingredients to your dish.",
        "item": "item",
        "ERR_ingredients_infos": "The informations are not precise enough. Fill every boxes please.",
        "ERR_dish_exists": "A saved dish already exists under this name.",
        "ERR_nb_invalid": "Enter a valid number",
        "price_kg": "Price per kilograms",
        "kg_needed": "Mass necessary",
        "price_l": "Price per liter",
        "l_needed": "Volume necessary",
        "item_price": "Price per item",
        "item_needed": "Number of items necessary",
        "dish_name": "Dish name",
        "items_per_packet": "Number of items in a paquet",
        "submit": "Submit",
        "cancel": "Cancel",
        "add_ingredient": "Add an ingredient",
        "remove_dish_title": "Dishes list - Select a dish to remove",
        "remove_dish": "Remove a dish from the list",
        "total": "Prix total",
        "export": "Export the shopping list"
    },
    "french": {
        "header_title": "Préparateur de liste de course",
        "restart_app": "Relancez l'application pour appliquer les changements",
        "dishes_list": "Liste des plats",
        "budget_cap": "Entre votre budget maximum",
        "dish_selector": "Ajoutez un repas",
        "add_dish": "Ajoutez un repas à la liste",
        "remove_elt": "Enelever un élément",
        "no_dish": "Aucun repas sélectionné",
        "ingredients": "Ingrédients",
        "ingredient_name": "Nom de l'ingrédient",
        "remove_entirely_elt": "Enlever entièrement l'élément",
        "next_meals": "Prochains repas:",
        "ERR_dish_name": "Veuillez entrer un nom de plat correct.",
        "ERR_dish_ingredients": "Veuillez entrer des ingrédients à votre plat.",
        "item": "unité",
        "ERR_ingredients_infos": "Les informations ne sont pas assez précises. Veuillez remplir toutes les cases.",
        "ERR_dish_exists": "Un plat enregistré existe déjà sous ce nom.",
        "ERR_nb_invalid": "Veuillez entrer un nombre valide",
        "price_kg": "Prix au kilogramme",
        "kg_needed": "Masse nécessaire",
        "price_l": "Prix au litre",
        "l_needed": "Volume nécessaire",
        "item_price": "Prix à l'unité",
        "item_needed": "Nombre d'unité nécessaire",
        "dish_name": "Nom du plat",
        "items_per_packet": "Nombre d'unité par paquet",
        "submit": "Soumettre",
        "cancel": "Annuler",
        "add_ingredient": "Ajouter un ingrédient",
        "remove_dish_title": "Liste des plats - sélectionner un plat à enlever de la liste",
        "remove_dish": "Enlever un plat de la liste",
        "total": "Prix total",
        "export": "Exporter la liste de course"
    }
}